name: WebRtcNativeLinuxSharedLib

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
     
    steps:
    - uses: actions/checkout@v3    
  
    - name: Remove unnecessary files
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
    
    - name: Create 'depot_tools'
      run: git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
    - name: Export 'depot_tools' path
      run: echo "${{github.workspace}}/depot_tools/" >> $GITHUB_PATH
    - name: Execute 'gclient'
      run: gclient
    
    - name: Configure Git
      run: |
        git config --global user.name "melihercan"
        git config --global user.email "melihercan@gmail.com"
        git config --global core.autocrlf false
        git config --global core.filemode false
        git config --global branch.autosetuprebase always
        
    - name: Get the code, patch and build
      run: |
        df -h
        mkdir webrtc-checkout
        cd webrtc-checkout
        fetch --nohooks webrtc
        gclient sync
        cd src
        git checkout branch-heads/5481
        gclient sync
        sed -i 's/rtc_static_library/rtc_shared_library/g' BUILD.gn
        sed -i '/complete_static_lib/d' BUILD.gn
        sed -i 's/!build_with_chromium && is_component_build/false/g' webrtc.gni
        sed -i '/:frame_analyzer/d' rtc_tools/BUILD.gn        
        gn gen out/Default --args="is_debug=false is_component_build=true rtc_enable_symbol_export=true rtc_include_tests=false rtc_build_tools=false rtc_build_examples=false"
        autoninja -C out/Default
        
    - name: Copy WebRTC library
      run: |
        cp webrtc-checkout/src/out/Default/libwebrtc.so .
        
    - uses: actions/upload-artifact@v3
      with: 
        name: Linux WebRTC shared library (libwebrtc.so)
        path: ./libwebrtc.so

